[16.0] Fix: xlrd version
camptocamp/docker-odoo-project pull request #239
Opened 2023-02-21 09:15 UTC by smussie

Context: the xlrd version 2.0.1 fails in odoo version 16, resulting in the error seen in the photo bellow. Resetting it back to the way odoo used it or using **xlrd >= 1.0.0** works, I tested in both cases.

![adiant_xlrd_version_fail](https://user-images.githubusercontent.com/29477079/220301335-245b1a3c-3310-4275-a7a1-65f395074ba2.png)

2023-02-21 09:43 UTC, leemannd approved these changes

2023-02-21 09:44 UTC, leemannd commented
It comes from  https://github.com/odoo/odoo/blob/16.0/requirements.txt#L46

2023-02-21 09:44 UTC, cyrilmanuel approved these changes

2023-02-21 09:56 UTC, vrenaville requested changes
You pointing on master, this branch is for the 5.X.X release, for the new images 

Please point your PR to release.4.5.X branch

2023-02-22 10:04 UTC, leemannd commented
@vrenaville quick question, shouldn't it be fixed also in new images?

2023-03-02 08:22 UTC, sebalix reviewed
Can you remove your fixup commit about pyOpenSSL and cryptography?
So we could merge only the fix of xlrd.

2023-03-06 07:23 UTC, smussie commented
> Can you remove your fixup commit about pyOpenSSL and cryptography? So we could merge only the fix of xlrd.

With great pleasure, because the pyOpenSSL and cryptograhy versions were giving me headache :)

2023-03-06 09:23 UTC, sebalix approved these changes

2023-03-06 09:23 UTC, sebalix commented
@vrenaville All good for you to merge? Will it possible to create a new release you think even with the build issue?

2023-03-06 10:53 UTC, vrenaville commented
@sebalix I'm ok if we are unable to fix it, in a short time. but if we need to downgrade xlrd, I will make a PR on master.

2023-03-06 10:53 UTC, vrenaville approved these changes

2023-03-08 12:20 UTC, merged